# Configuration

title = "Software and Math"

baseurl = "https://vchernoy.xyz/"  # End your URL with a `/` trailing slash.
publishDir = "public"
themesDir = "themes"
buildDrafts = false


theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
paginate = 10

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-102853829-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

enableGitInfo = true

#[blackfriday]
#  hrefTargetBlank = true

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  fractions = true  # `false` disables smart fractions (e.g. 5/12 formatted as a fraction).
  smartypants = true  # `false` disables all smart punctuation substitutions (e.g. smart quotes, dashes, fractions).
  extensions = ["backslashLineBreak"]


[params]
  name = "Slava Chernoy"
  role = "Software Engineer"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering?
  math = true

  highlight = true
  highlight_languages = ["go", "python", "rust", "scala", "bash", "cpp", "java", "dockerfile", "ebnf", "protobuf", "sql", "thrift", "yaml"]
  highlight_version = "9.12.0"
  highlight_style = "idea"

  # Enable native social sharing buttons?
  sharing = false

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # Social/Academic Networking
  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://linkedin.com/in/slava-chernoy-9859a81/"

  [[params.social]]
    icon = "google-scholar"
    icon_pack = "ai"
    link = "https://scholar.google.co.uk/citations?user=3tWEfksAAAAJ"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "https://github.com/vchernoy"

  [[params.social]]
    icon = "stack-overflow"
    icon_pack = "fa"
    link = "https://stackoverflow.com/users/276287/slava"

  [[params.social]]
    icon = "dblp"
    icon_pack = "ai"
    link = "http://dblp.uni-trier.de/pers/hd/c/Chernoy:Viacheslav"

  [[params.social]]
    icon = "springer"
    icon_pack = "ai"
    link = "https://link.springer.com/search?query=Viacheslav+Chernoy"

# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[params.menus]
  # Align the main menu to the right of the page? (true/false)
  align_right = true

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
